language: python

python:
- '2.7'

env:
  global:
  - secure: "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
  - secure: "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"

branches:
  only:
  - master

script: ./scripts/build.sh

deploy:
  provider: s3
  access_key_id: $AWSAKEY
  secret_access_key: $AWSSKEY
  bucket: "awsebcli.foo.com"
  skip_cleanup: true
  local-dir: target
  on:
    branch: master
